services:
  app:
    build:
      context: ./app
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: ./app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

# Named volumes - this can create a persistnt storage location managed by docker
# This will persist data between restarts
# TODO: dive a bit more into persistent storage
volumes:
  db-data:
