services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile  # Point to Dockerfile.debug for debugging
    ports:
      - 127.0.0.1:8080:8080
      # - 127.0.0.1:40000:40000        # Port for Delve debugger
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - ./app:/app
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./app
    #       target: ./app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

# Named volumes - this can create a persistnt storage location managed by docker
# This will persist data between restarts
# TODO: dive a bit more into persistent storage
volumes:
  db-data:
